# name: Publish to GitHub Pages

# on:
#   push:
#   pull_request:

# permissions:
#   contents: write

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       BASE_URL: GOSTrocks
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.10"
#           cache: "pip"
#       - name: Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           python -m pip install jupyter-book
#           if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
#       - name: Build Jupyter book v2
#         run: |
#           cd docs
#           jupyter book build --html --strict
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         if: github.ref == 'refs/heads/main' && job.status == 'success'
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./docs/_build/html
#           enable_jekyll: false
